config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'home/index'
  
  root to: "categories#index"
  mount ActionCable.server => '/cable'
  resources :categories do
    resources :products do
      resources :comments do
        post 'create_reply', on: :member
        delete 'destroy_reply', on: :member
      end
    end
  end
  resources :carts
  post 'carts/add_selected_products', to: 'carts#add_selected_products', as: :add_selected_products_to_cart
  resources :cart_items
  match '*unmatched', to: 'application#not_found_method', via: :all
  
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products, dependent: :destroy
end

app/controllers/categories_controller.rb
    # app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :update, :destroy]
    before_action :authorize_category, except:[:create, :new, :index]
  
    def index
      @categories = Category.all
      if current_user
        if current_user.admin?||current_user.seller?
          authorize @categories
        else
          authorize @categories
        end
      else
        authorize @categories
      end
    end
  
    def new
      @category = Category.new
      if current_user
        if current_user.admin?||current_user.seller?
          authorize @category
        else
        # If not an admin, assume the user is a buyer
          authorize @category
        end
      else
        authorize @category
      end
    end
  
    def create
      @category = Category.new(category_params)
      if current_user
        if current_user.admin?||current_user.seller?
          authorize @category
          if @category.save
            redirect_to categories_path, notice: 'Category was successfully created.'
          else
            render :new
          end

        else
          authorize @category
        end
      else
        authorize @category
      end

      
    end
  
    def edit
     
    end
  
    def update
      
      @category = Category.find(params[:id])
      if current_user
        if current_user.admin?||(current_user.seller?)
         
          if @category.update(category_params)
            redirect_to categories_path, notice: 'Category was successfully updated.'
          else
            render :edit
          end
     
        end
   
      end
  
    end
  
    def destroy
      if current_user
        if current_user.admin?||(current_user.seller?)
          
          @category.destroy
          redirect_to categories_url, notice: 'Category was successfully deleted.'
        
        end
     
      end
      
    end
  

  
    private
  
    def set_category
      @category = Category.find(params[:id])
    end
    def category_params
      params.require(:category).permit(:name, :description)
    end
    def authorize_category
    
      authorize @category
      
    end
end
  

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/create.html.erb
<!-- app/views/categories/create.html.erb -->

<div class="mt-8">
  <h2 class="text-2xl font-bold text-gray-800">Create New Category</h2>

  <%= form_for(@category, html: { class: "mt-4" }) do |f| %>
    <%# Category Name Field %>
    <div class="mt-4">
      <%= f.label :name, class: "block font-semibold text-gray-800" %>
      <%= f.text_field :name, class: "form-input mt-1 block w-full" %>
    </div>

  
    <div class="mt-4">
      <%= f.submit 'Create Category', class: "bg-blue-500 text-white font-bold px-4 py-2 rounded hover:bg-blue-600 transition-colors duration-300" %>
    </div>
  <% end %>

  <%= link_to 'Back', categories_path, class: "mt-4 bg-gray-500 text-white font-bold px-4 py-2 rounded hover:bg-gray-600 transition-colors duration-300" %>
</div>

app/views/categories/destroy.html.erb
<!-- app/views/categories/destroy.html.erb -->
<h1>Delete Category</h1>
<p>Are you sure you want to delete the category "<%= @category.name %>"?</p>
<%= link_to 'Delete', category_path(@category), method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Cancel', categories_path %>

app/views/categories/edit.html.erb
<h1 class="text-4xl font-bold text-gray-800">Edit Category</h1>

<%= form_with(model: @category, url: category_path(@category), method: :patch) do |form| %>
  <div class="mt-4">
    <%= form.label :name, class: "text-xl" %><br />
    <%= form.text_field :name, class: "w-full px-4 py-2 border rounded-md focus:outline-none focus:ring focus:border-blue-300" %>
  </div>

  <div class="mt-4">
    <%= form.label :description, class: "text-xl" %><br />
    <%= form.text_area :description, class: "w-full px-4 py-2 border rounded-md focus:outline-none focus:ring focus:border-blue-300" %>
  </div>

  <div class="mt-4">
    <%= form.submit "Update Category", class: "px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 transition-colors duration-300" %>
  </div>
<% end %>

app/views/categories/index.html.erb
<h1 class="text-4xl font-bold text-gray-800">All Categories</h1>

<table class="mt-4 w-full border-collapse">
  <thead>
    <tr>
      <th class="text-xl px-4 py-2 border">Name</th>
      <th class="text-xl px-4 py-2 border">Description</th>
      <th class="text-xl px-4 py-2 border">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td class="text-xl px-4 py-2 border"><%= category.name %></td>
        <td class="text-xl px-4 py-2 border"><%= category.description %></td>
        <td class="px-4 py-2 border flex">
          <%= link_to 'View Products', category_products_path(category), class: 'px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 transition-colors duration-300' %>
          <%if policy(category).edit?%>
          <%= link_to 'Edit', edit_category_path(category), class: 'ml-2 px-4 py-2 bg-green-500 text-white rounded-md hover:bg-green-600 transition-colors duration-300' %>
          <%end%>
          <%if policy(category).destroy?%>
          <%= form_with(model: category, url: category_path(category), method: :delete, data: { confirm: 'Are you sure you want to delete this category?' }) do |form| %>
            <%= form.submit 'Delete', class: 'ml-2 px-4 py-2 bg-red-500 text-white rounded-md hover:bg-red-600 transition-colors duration-300' %>
          <%end%>
          <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="mt-4">
  <%if policy(Category).create?%>
  <%= link_to 'Add Category', new_category_path, class: 'px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-indigo-600 transition-colors duration-300' %>
  <%end%>
</div>
<div class="mt-4">
  <%if user_signed_in?%>
  <%= link_to 'Go to Cart', carts_path, class: 'px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-indigo-600 transition-colors duration-300' %>
  <%end%>
</div>

app/views/categories/new.html.erb
<!-- app/views/categories/create.html.erb -->

<div class="mt-8">
  <h2 class="text-2xl font-bold text-gray-800">Create New Category</h2>

  <%= form_for(@category, html: { class: "mt-4" }) do |f| %>
    <%# Category Name Field %>
    <div class="mt-4">
      <%= f.label :name, class: "block font-semibold text-gray-800" %>
      <%= f.text_field :name, class: "form-input mt-1 block w-full" %>
    </div>

    <%# Other Category Fields %>
  

    <div class="mt-4">
      <%= f.submit 'Create Category', class: "bg-blue-500 text-white font-bold px-4 py-2 rounded hover:bg-blue-600 transition-colors duration-300" %>
    </div>
  <% end %>

  <%= link_to 'Back', categories_path, class: "mt-4 bg-gray-500 text-white font-bold px-4 py-2 rounded hover:bg-gray-600 transition-colors duration-300" %>
</div>