config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'home/index'
  
  root to: "categories#index"
  mount ActionCable.server => '/cable'
  resources :categories do
    resources :products do
      resources :comments do
        post 'create_reply', on: :member
        delete 'destroy_reply', on: :member
      end
    end
  end
  resources :carts
  post 'carts/add_selected_products', to: 'carts#add_selected_products', as: :add_selected_products_to_cart
  resources :cart_items
  match '*unmatched', to: 'application#not_found_method', via: :all
  
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category
    belongs_to :user
    has_many :cart_items, dependent: :destroy
    has_many :carts, through: :cart_items
    has_many :comments, dependent: :destroy
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_category
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authorize_product, except:[:create, :new, :index]

  def index
    @products = @category.products
  end

  def show
   
    @product = Product.includes(comments: :user).find(params[:id])
  end

  def new
    @product = @category.products.new
  end

  def create
    @product = @category.products.new(product_params)
    @product.user_id=current_user.id
    if current_user
      if current_user.admin?||current_user.seller?
        authorize @product
        if @product.save
          redirect_to category_product_path(@category, @product), notice: 'Product was successfully created.'
        else
          render :new
        end
      else
        authorize @product
      end
    else
      authorize @product
    end


  end

  def edit
  end

  def update
    if current_user
      if current_user.admin?||(current_user.seller?)
       
        if @product.update(product_params)
        ActionCable.server.broadcast 'product_channel', {product_id: @product.id, price: @product.price, method: "update" }
        redirect_to category_product_path(@category, @product), notice: 'Product was successfully updated.'
        else
        render :edit
        end
 
       end
 
     end

  end

  def destroy
    if current_user
      if current_user.admin?||(current_user.seller?)
     
        @product.destroy
        redirect_to category_products_path(@category), notice: 'Product was successfully deleted.'
   
      end
 
    end
  end


  private

  def set_category
    @category = Category.find(params[:category_id])
  end

  def set_product
    @product = @category.products.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price)
  end
  def authorize_product
    authorize @product
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<h1 class="text-4xl font-bold text-gray-800 mb-4">Update Product</h1>

<%= form_with(model: [@category, @product]) do |form| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2 class="text-red-500"><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul class="text-red-500">
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mb-4">
    <%= form.label :name, class: "block text-xl font-medium text-gray-800" %>
    <%= form.text_field :name, class: "form-input mt-1 block w-full rounded-md border-gray-300" %>
  </div>

  <div class="mb-4">
    <%= form.label :description, class: "block text-xl font-medium text-gray-800" %>
    <%= form.text_area :description, class: "form-textarea mt-1 block w-full rounded-md border-gray-300" %>
  </div>

  <div class="mb-4">
    <%= form.label :price, class: "block text-xl font-medium text-gray-800" %>
    <%= form.text_area :price, class: "form-textarea mt-1 block w-full rounded-md border-gray-300" %>
  </div>

  <div class="actions">
    <%= form.submit "Update Product", class: "px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 transition-colors duration-300" %>
  </div>
<% end %>

app/views/products/index.html.erb
<h1 class="text-4xl font-bold text-gray-800 mb-4">All Products in <%= @category.name %> Category</h1>

<table class="w-full border-collapse">
  <thead>
    <tr>
      <th class="px-4 py-2">Name</th>
      <th class="px-4 py-2">Description</th>
      <th class="px-4 py-2">Category</th>
      <th class="px-4 py-2">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td class="px-4 py-2">
          <%= link_to product.name, category_product_path(@category, product), class: "text-blue-500 hover:underline" %>
        </td>
        <td class="px-4 py-2"><%= product.description %></td>
        <td class="px-4 py-2"><%= product.category.name %></td>
        <td class="px-4 py-2">
          <div class="flex">
          <%if policy(product).edit?%>
            <%= form_with(model: product, url: edit_category_product_path(@category, product), method: :get) do |form| %>
              <%= form.submit 'Edit', class: 'bg-blue-500 text-white px-3 py-1 rounded-md hover:bg-blue-600 transition-colors duration-300 mr-2' %>
            <% end %>
          <%end%>

            <!-- Delete Button -->
            <%if policy(product).destroy?%>
            <%= form_with(model: product, url: category_product_path(@category, product), method: :delete) do |form| %>
              <%= form.submit 'Delete', class: 'bg-red-500 text-white px-3 py-1 rounded-md hover:bg-red-600 transition-colors duration-300' %>
            <% end %>
            <%end%>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%if policy(Product).create?%>
<%= link_to "New Product", new_category_product_path(@category), class: "bg-green-500 text-white px-4 py-2 rounded-md hover:bg-green-600 transition-colors duration-300 mt-4" %>
<%end%>
<%= link_to "Back to Categories", categories_path, class: "bg-gray-500 text-white px-4 py-2 rounded-md hover:bg-gray-600 transition-colors duration-300 ml-4 mt-4" %>

app/views/products/new.html.erb
<h1 class="text-4xl font-bold text-gray-800 mb-4">New Product</h1>

<%= form_with(model: [@category, @product]) do |form| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2 class="text-red-500"><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul class="text-red-500">
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mb-4">
    <%= form.label :name, class: "block text-xl font-medium text-gray-800" %>
    <%= form.text_field :name, class: "form-input mt-1 block w-full rounded-md border-gray-300" %>
  </div>

  <div class="mb-4">
    <%= form.label :description, class: "block text-xl font-medium text-gray-800" %>
    <%= form.text_area :description, class: "form-textarea mt-1 block w-full rounded-md border-gray-300" %>
  </div>

    <div class="mb-4">
    <%= form.label :price, class: "block text-xl font-medium text-gray-800" %>
    <%= form.text_area :price, class: "form-textarea mt-1 block w-full rounded-md border-gray-300" %>
  </div>

  <div class="actions">
    <%= form.submit "Create Product", class: "px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 transition-colors duration-300" %>
  </div>
<% end %>

app/views/products/show.html.erb
<h1 class="text-4xl font-bold text-gray-800"><%= @product.name %></h1>
<p class="text-lg text-gray-600"><%= @product.description %></p>
<p data-myproduct-id="<%=@product.id%>" class="text-lg text-red-600"><%= @product.price %></p>

<h2 >Comments</h2>
<div>
  <% @product.comments.each do |comment| %>
  <% if comment.parent_comment_id.nil? %>
    <div class="<%= comment.id %>" data-comment-id="<%= comment.id %>"  id="comments" data-product-id="<%= @product.id %>">
    <div >
    <div>
      <%# <% user = User.find_by(id: comment.user_id) %> 
      <%# <%= user.name if user %> 
       <%= comment.user.name if comment.user %>
    </div>
    <div >  
    <%# this is changed %>
      <span class="comment-content"><%= comment.content %></span> 
      <% if policy(comment).edit? %>
        <%= link_to "Edit", edit_category_product_comment_path(@category, @product, comment), class: "text-blue-500 font-bold mr-2" %>
        <%= form_with(model: comment, url: category_product_comment_path(@category, @product, comment), method: :delete, html: { class: "inline" }) do |form| %>
          <%= form.submit 'Delete', class: 'text-red-500 font-bold' %>
        <% end %>
      <% end %>
    </div>
  </div>
  
  <% comment.replies.each do |reply| %>
  <div data-reply-id="<%= reply.id %>">
    <div>
      <%# <% user = User.find_by(id: reply.user_id) %> 
      <%# <%= user.name if user %>  
      <%= reply.user.name if reply.user %>
    </div>
    <div>
      <%= reply.content %>
      <% if policy(reply).edit? %>
      <%= link_to "Edit", edit_category_product_comment_path(@category, @product, reply), class: "text-blue-500 font-bold mr-2" %> 
      <%= link_to "Delete", destroy_reply_category_product_comment_path(@category, @product, reply), method: :delete, data: { "turbo-method": :delete }, class: "text-red-500 font-bold" %> 
      <% end %>
    </div>
  </div>
  <% end %>
  <% if user_signed_in?%>
  <%= form_with(model: [comment, comment.replies.build], url: create_reply_category_product_comment_path(@category, @product, comment)) do |form| %>
  <div>
    <%= form.label :reply %>
    <%= form.text_area :content, class: "form-textarea" %>
  </div>
  <div>
    <%= form.submit 'Add Reply', class: 'bg-blue-500 text-white font-bold px-4 py-2 rounded' %>
  </div>
  <% end %>
  <% end %>
  <%end%>
  <%end%>
</div>
</div>
</div>
<%if user_signed_in?%>
<%= form_with(model: [@product, @product.comments.build], url: category_product_comments_path(@category, @product)) do |form| %>
  <div>
    <%= form.label :Comment %>
    <%= form.text_area :content, class: "form-textarea" %>
  </div>
  <div>
    <%= form.submit 'Add Comment', class: 'bg-blue-500 text-white font-bold px-4 py-2 rounded' %>
  </div>
<% end %>
<% end %>
<%= link_to 'Back to Products', category_products_path, class: 'mt-20 bg-blue-500 text-white font-bold px-4 py-2 rounded' %>